Fixed issues with dlApi, and test scripts
onetads/shoper-plugin pull request #2
Opened 2023-12-14 11:37 UTC by przemyslawczachor-fingoweb

Fixed some issues like:

- unnecessary dlApi script inject,
- removed static websiteId argument
- dlApi addKeyValue method usage instead of simple value assignment
- dlApi cmd proper implementation
- added missing build for testing purposes

2023-12-14 15:05 UTC, ravkr commented on src/index.ts
> +if (isTestingEnvironment) {
Jak dobrze rozumiem, to obecnie zakładacie, że dodanie skryptu przez `<script>` (albo w bezpośrednio kodzie strony) oznacza uruchomienie "produkcyjne", a dodanie skryptu po czasie (wklejenie do konsoli, lub osadzenie tego skryptu przez inny skrypt) oznacza uruchomienie "testowe".
Jednak to powinno **zawsze** móc działać produkcyjnie - ten skrypt będzie czasami osadzany przez naszą bibliotekę (bez konfiguracji przez App Store Shopera)

2023-12-14 15:10 UTC, ravkr commented on src/managers/AdManager/AdManager.ts
> +      dlApi.addKeyValue('area', area || '');
tutaj użycie `dlApi.area` było ok.
Metoda `dlApi.addKeyValue` służy konkretnie do ustawiania danych w `dlApi.keyvalues`, a nie do wszystkiego w `dlApi`
więc przykładowo można tego użyć tak:
```js
console.log('foo:', dlApi.keyvalues['foo']) // "foo: undefined"
dlApi.addKeyValue('foo', 'bar')
console.log('foo:', dlApi.keyvalues['foo']) // "foo: bar"
```

2023-12-14 15:17 UTC, ravkr commented on src/managers/AdManager/AdManager.ts
> +      .then((result) => {
ten `then` chyba nic nie robi?

2023-12-14 20:28 UTC, dpiwko19 commented on src/consts/replaceMap.ts
> +          selector: '.basket',
uszczuplenie  tego selectora rozumiem, że nie wpływa na działanie? I nie ma żadnego corner case'u, który spowoduje błąd?

2023-12-15 07:48 UTC, ODudek requested changes

2023-12-15 07:48 UTC, ODudek commented on src/managers/AdManager/AdManager.ts
> +      dlApi.addKeyValue('keyvalues', {
Należy zmienić parametry z którymi jest wywołana metoda `addKeyValue` aby zadziałała poprawnie na

```suggestion
      dlApi.addKeyValue('offer_ids', this.productsIds.toString())
```

2023-12-15 07:48 UTC, ODudek commented on src/managers/AdManager/AdManager.ts
> +      dlApi.addKeyValue('area', area || '');
Tak jak napisał @ravkr tutaj należy poprawić tę linijkę na
```suggestion
      dlApi.area = area || 'ros'
```

`ros` powinien być domyślną wartością w przypadku gdy nie uda się zmapować wartości na `area`

2024-01-09 13:50 UTC, skoklowski commented on src/managers/AdManager/AdManager.ts
> +      dlApi.addKeyValue('offer_ids', this.productsIds.toString());
Ta wartość powinna być przekazana do funkcji `dlApi.fetchNativeAd` jako argument `options.opts.offer_ids` (nie ma potrzeby rzutowania na string). W przeciwnym razie mogłoby się zdarzyć, że wszystkie pozostałe reklamy w ramach RMN byłyby zawsze dopasowane kontekstowo do podanych ofert, a takie zachowanie nie zawsze będzie korzystne.

Poza tym jeśli to już by miało być w tym miejscu, to powinno wyglądać tak:
```js
(dlApi.cmd = dlApi.cmd || []).push(function() {
    dlApi.addKeyValue('offer_ids', this.productsIds.toString());
});
```
W przeciwnym razie w tej linijce będzie *race condition* - czasem będzie działać poprawnie, a innym razem dostaniemy błąd:
> TypeError: dlApi.addKeyValue is not a function

2024-01-09 14:12 UTC, skoklowski commented on src/managers/AdManager/AdManager.ts
> +      dlApi.addKeyValue('offer_ids', this.productsIds.toString());
Docelowo będzie trzeba to przenieść do funkcji `dlApi.fetchNativeAd` - do argumentu `options.opts.offer_ids`. W przeciwnym razie wszystkie inne reklamy RMN na tej samej stronie (np. Promo Banner) również będą dopasowane kontekstowo do podanych ofert, a nie zawsze tego chcemy.

2024-01-26 11:17 UTC, merged